Add support for ARIA product v3 correction layers in prep_aria
insarlab/MintPy pull request #1247
Opened 2024-08-03 07:15 UTC by sssangha

**Description of proposed changes**

**Reminders**

- [ ] Fix #xxxx
- [ ] Pass Pre-commit check (green)
- [ ] Pass Codacy code review (green)
- [ ] Pass Circle CI test (green)
- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] If modifying functionality, describe changes to function behavior and arguments in a comment below the function declaration.
- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.

2024-08-13 20:02 UTC, dbekaert commented
@sssangha @yunjunz Can we move this PR along? Any updated needed @yunjunz?

2024-08-15 07:45 UTC, yunjunz commented on src/mintpy/cli/prep_aria.py
>    # reference: https://github.com/aria-tools/ARIA-tools
Could you provide an example command to show how to download a dataset with these correction layers?

2024-08-15 07:49 UTC, yunjunz commented on src/mintpy/prep_aria.py
> +def write_iono_stack(outfile, ionStack, box=None,
This function is almost the same as the `write_ifgram_stack()`, could you re-use it instead of creating a new one?

2024-08-15 08:01 UTC, yunjunz requested changes
Thank you @sssangha and @mgovorcin for the PR. Besides the comments above, could you also fix the suggestions from pre-commit and codacy checking?

2024-08-15 08:01 UTC, yunjunz commented on src/mintpy/prep_aria.py
> +def write_model_stack(outfile, corrStack, box=None,
```suggestion
def write_timeseries(outfile, corrStack, box=None, 
```

2024-09-09 02:59 UTC, yunjunz commented
@sssangha @dbekaert I have made some suggestions for this PR. It would be great if it can be updated and moved forward.

2024-11-01 17:36 UTC, EJFielding commented
I hope this addition can be completed soon. We can really use this ionospheric layer support to advance our NISAR Calibration and Validation activities that use ARIA S1-GUNW files.

2024-11-11 19:34 UTC, mgovorcin commented on src/mintpy/cli/prep_aria.py
> +    corr.add_argument('--cluster', dest='cluster', type=str, choices={'local', 'pbs', None},
do we need  arguments cluster and num-workers as network inversion of iono stack should be outside of this script

2024-11-11 19:37 UTC, mgovorcin commented on src/mintpy/prep_aria.py
> +            print(stackFiles.keys())
remove or change print with Mintpy logging/verbose (vprint)

2024-11-11 19:40 UTC, mgovorcin commented on src/mintpy/prep_aria.py
> +def write_timeseries(outfile, corrStack, box=None,
add description and type for the function arguments

2024-11-11 19:55 UTC, mgovorcin approved these changes
All @yunjunz  suggestions have been addressed, please remove unused args from `cli/prep_aria.py` before the merge.

2024-11-12 02:48 UTC, yunjunz commented
> All @yunjunz suggestions have been addressed, please remove unused args from `cli/prep_aria.py` before the merge.

Great. I tried to test it last week, but the environment needs to be updated for the new ARIA-tools. I will try it again this weekend.

2024-11-12 03:07 UTC, EJFielding commented
We found recently that the conda-forge ARIA-tools requires Python 3.12 but ISCE2 only allows versions up to 3.11, so it is not presently possible to make a conda environment with ISCE2, ARIA-tools, and MintPy.

2024-11-12 03:13 UTC, yunjunz commented
Thanks for the heads-up @EJFielding, I will create a new env for this test then.

2024-12-17 20:00 UTC, ehavazli commented
Hi @yunjunz and @EJFielding, what's the current status of this PR on your end?

2024-12-19 00:54 UTC, yunjunz commented
> Hi @yunjunz and @EJFielding, what's the current status of this PR on your end?

I won't have time to test the change in the coming few days. Since the PR only changes code in `prep_aria`, it's fine with me to merge as long as others confirm it works. @EJFielding ?

2025-01-21 20:35 UTC, ehavazli commented
@EJFielding reported issues with loading the troposphere is ionosphere stacks. I wasn't able to duplicate the issue and successfully loaded both stacks to MintPy. We can tackle the problem via issue tickets if the problem persists.

2025-01-21 20:35 UTC, ehavazli approved these changes

2025-01-21 20:37 UTC, merged