save_hdfeos5.py and smallbaselineApp.py: adding avgSpatialCoh.h5 file to S1*.he5 file
insarlab/MintPy pull request #434
Opened 2020-09-04 03:31 UTC by ranneylxr

**Description of proposed changes**

save_hdfeos5.py and smallbaselineApp.py: adding avgSpatialCoh.h5 file to S1*.he5 file

**Reminders**
- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.

2020-09-04 03:35 UTC, yunjunz commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- mintpy/save_hdfeos5.py  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/insarlab/MintPy/pullRequest?prid=6122943&bid=20032601)

2020-09-04 04:54 UTC, yunjunz commented on mintpy/save_hdfeos5.py
> +                        help='Average spatial coherence file, i.e. avgSpatialCoh.h5')
All options with more than one character are with two "-" in mintpy, could you adjust these two also?

2020-09-04 04:56 UTC, yunjunz requested changes
There is a conflict identified in smallbaselineApp.py, could you resolve it?

2020-09-06 08:45 UTC, ranneylxr commented
Hi Yunjun,
Sorry, I just saw these comments. I changed the '-tc' and '-asc' to '--tc' and '--asc', and solve the conflicts about smallbaselineApp.py.
Please check.

2020-09-06 08:48 UTC, closed without merging

2020-09-06 22:16 UTC, yunjunz commented
Hi @ranneylxr, no worries at all. Thank you for contributing!

BTW, to update a PR, you can simply keep updating the feature you were working on in your fork, then the attached PR will be updated automatically, no need to close and issue a new PR. Check the [contributing guide](https://github.com/insarlab/MintPy/blob/main/docs/CONTRIBUTING.md#4-review-process) if you are interested.